using Babble.Core.Enums;

namespace Babble.Core.Settings;

public static class BabbleAddresses
{
    public static readonly Dictionary<UnifiedExpression, string> Addresses = new()
    {
        {
            UnifiedExpression.CheekPuffLeft,
            "/cheekPuffLeft"
        },
        {
            UnifiedExpression.CheekPuffRight,
            "/cheekPuffRight"
        },
        {
            UnifiedExpression.CheekSuckLeft,
            "/cheekSuckLeft"
        },
        {
            UnifiedExpression.CheekSuckRight,
            "/cheekSuckRight"
        },
        {
            UnifiedExpression.JawOpen,
            "/jawOpen"
        },
        {
            UnifiedExpression.JawForward,
            "/jawForward"
        },
        {
            UnifiedExpression.JawLeft,
            "/jawLeft"
        },
        {
            UnifiedExpression.JawRight,
            "/jawRight"
        },
        {
            UnifiedExpression.NoseSneerLeft,
            "/noseSneerLeft"
        },
        {
            UnifiedExpression.NoseSneerRight,
            "/noseSneerRight"
        },
        {
            UnifiedExpression.LipFunnelLowerLeft,
            "/mouthFunnel"
        },
        {
            UnifiedExpression.LipFunnelLowerRight,
            "/mouthFunnel"
        },
        {
            UnifiedExpression.LipFunnelUpperLeft,
            "/mouthFunnel"
        },
        {
            UnifiedExpression.LipFunnelUpperRight,
            "/mouthFunnel"
        },
        {
            UnifiedExpression.LipPuckerLowerLeft,
            "/mouthPucker"
        },
        {
            UnifiedExpression.LipPuckerLowerRight,
            "/mouthPucker"
        },
        {
            UnifiedExpression.LipPuckerUpperLeft,
            "/mouthPucker"
        },
        {
            UnifiedExpression.LipPuckerUpperRight,
            "/mouthPucker"
        },
        {
            UnifiedExpression.MouthUpperLeft,
            "/mouthLeft"
        },
        {
            UnifiedExpression.MouthLowerLeft,
            "/mouthLeft"
        },
        {
            UnifiedExpression.MouthUpperRight,
            "/mouthRight"
        },
        {
            UnifiedExpression.MouthLowerRight,
            "/mouthRight"
        },
        {
            UnifiedExpression.LipSuckUpperLeft,
            "/mouthRollUpper"
        },
        {
            UnifiedExpression.LipSuckUpperRight,
            "/mouthRollUpper"
        },
        {
            UnifiedExpression.LipSuckLowerLeft,
            "/mouthRollLower"
        },
        {
            UnifiedExpression.LipSuckLowerRight,
            "/mouthRollLower"
        },
        {
            UnifiedExpression.MouthRaiserUpper,
            "/mouthShrugUpper"
        },
        {
            UnifiedExpression.MouthRaiserLower,
            "/mouthShrugLower"
        },
        {
            UnifiedExpression.MouthClosed,
            "/mouthClose"
        },
        {
            UnifiedExpression.MouthCornerPullLeft,
            "/mouthSmileLeft"
        },
        {
            UnifiedExpression.MouthCornerPullRight,
            "/mouthSmileRight"
        },
        {
            UnifiedExpression.MouthFrownLeft,
            "/mouthFrownLeft"
        },
        {
            UnifiedExpression.MouthFrownRight,
            "/mouthFrownRight"
        },
        {
            UnifiedExpression.MouthDimpleLeft,
            "/mouthDimpleLeft"
        },
        {
            UnifiedExpression.MouthDimpleRight,
            "/mouthDimpleRight"
        },
        {
            UnifiedExpression.MouthUpperUpLeft,
            "/mouthUpperUpLeft"

        },
        {
            UnifiedExpression.MouthUpperUpRight,
            "/mouthUpperUpRight"
        },
        {
            UnifiedExpression.MouthLowerDownLeft,
            "/mouthLowerDownLeft"
        },
        {
            UnifiedExpression.MouthLowerDownRight,
            "/mouthLowerDownRight"
        },
        {
            UnifiedExpression.MouthPressLeft,
            "/mouthPressLeft"
        },
        {
            UnifiedExpression.MouthPressRight,
            "/mouthPressRight"
        },
        {
            UnifiedExpression.MouthStretchLeft,
            "/mouthStretchLeft"
        },
        {
            UnifiedExpression.MouthStretchRight,
            "/mouthStretchRight"
        },
        {
            UnifiedExpression.TongueOut,
            "/tongueOut"
        },
        {
            UnifiedExpression.TongueUp,
            "/tongueUp"
        },
        {
            UnifiedExpression.TongueDown,
            "/tongueDown"
        },
        {
            UnifiedExpression.TongueLeft,
            "/tongueLeft"
        },
        {
            UnifiedExpression.TongueRight,
            "/tongueRight"
        },
        {
            UnifiedExpression.TongueRoll,
            "/tongueRoll"
        },
        {
            UnifiedExpression.TongueBendDown,
            "/tongueBendDown"
        },
        {
            UnifiedExpression.TongueCurlUp,
            "/tongueCurlUp"
        },
        {
            UnifiedExpression.TongueSquish,
            "/tongueSquish"
        },
        {
            UnifiedExpression.TongueFlat,
            "/tongueFlat"
        },
        {
            UnifiedExpression.TongueTwistLeft,
            "/tongueTwistLeft"
        },
        {
            UnifiedExpression.TongueTwistRight,
            "/tongueTwistRight"
        }
    };
}

