using Babble.Core.Enums;

namespace Babble.OSC.Expressions;

public class UnifiedExpressionToFloatMapping
{
    public static readonly Dictionary<UnifiedExpression, float> Expressions = new Dictionary<UnifiedExpression, float>
    {
        { UnifiedExpression.CheekPuffLeft, 0f },
        { UnifiedExpression.CheekPuffRight, 0f },
        { UnifiedExpression.CheekSuckLeft, 0f },
        { UnifiedExpression.CheekSuckRight, 0f },
        { UnifiedExpression.JawOpen, 0f },
        { UnifiedExpression.JawForward, 0f },
        { UnifiedExpression.JawLeft, 0f },
        { UnifiedExpression.JawRight, 0f },
        { UnifiedExpression.NoseSneerLeft, 0f },
        { UnifiedExpression.NoseSneerRight, 0f },
        { UnifiedExpression.LipFunnelLowerLeft, 0f },
        { UnifiedExpression.LipFunnelLowerRight, 0f },
        { UnifiedExpression.LipFunnelUpperLeft, 0f },
        { UnifiedExpression.LipFunnelUpperRight, 0f },
        { UnifiedExpression.LipPuckerLowerLeft, 0f },
        { UnifiedExpression.LipPuckerLowerRight, 0f },
        { UnifiedExpression.LipPuckerUpperLeft, 0f },
        { UnifiedExpression.LipPuckerUpperRight, 0f },
        { UnifiedExpression.MouthUpperLeft, 0f },
        { UnifiedExpression.MouthLowerLeft, 0f },
        { UnifiedExpression.MouthUpperRight, 0f },
        { UnifiedExpression.MouthLowerRight, 0f },
        { UnifiedExpression.LipSuckUpperLeft, 0f },
        { UnifiedExpression.LipSuckUpperRight, 0f },
        { UnifiedExpression.LipSuckLowerLeft, 0f },
        { UnifiedExpression.LipSuckLowerRight, 0f },
        { UnifiedExpression.MouthRaiserUpper, 0f },
        { UnifiedExpression.MouthRaiserLower, 0f },
        { UnifiedExpression.MouthClosed, 0f },
        { UnifiedExpression.MouthCornerPullLeft, 0f },
        { UnifiedExpression.MouthCornerPullRight, 0f },
        { UnifiedExpression.MouthFrownLeft, 0f },
        { UnifiedExpression.MouthFrownRight, 0f },
        { UnifiedExpression.MouthDimpleLeft, 0f },
        { UnifiedExpression.MouthDimpleRight, 0f },
        { UnifiedExpression.MouthUpperUpLeft, 0f },
        { UnifiedExpression.MouthUpperUpRight, 0f },
        { UnifiedExpression.MouthLowerDownLeft, 0f },
        { UnifiedExpression.MouthLowerDownRight, 0f },
        { UnifiedExpression.MouthPressLeft, 0f },
        { UnifiedExpression.MouthPressRight, 0f },
        { UnifiedExpression.MouthStretchLeft, 0f },
        { UnifiedExpression.MouthStretchRight, 0f },
        { UnifiedExpression.TongueOut, 0f },
        { UnifiedExpression.TongueUp, 0f },
        { UnifiedExpression.TongueDown, 0f },
        { UnifiedExpression.TongueLeft, 0f },
        { UnifiedExpression.TongueRight, 0f },
        { UnifiedExpression.TongueRoll, 0f },
        { UnifiedExpression.TongueBendDown, 0f },
        { UnifiedExpression.TongueCurlUp, 0f },
        { UnifiedExpression.TongueSquish, 0f },
        { UnifiedExpression.TongueFlat, 0f },
        { UnifiedExpression.TongueTwistLeft, 0f },
        { UnifiedExpression.TongueTwistRight, 0f  }
    };
}
