    using Babble.Core.Enums;
    using Babble.OSC.Collections;

    namespace Babble.OSC;

    public partial class BabbleOSC
    {
        public static readonly TwoKeyDictionary<UnifiedExpression, string, float> Expressions = new()
        {
            {
                UnifiedExpression.CheekPuffLeft,
                "/cheekPuffLeft",
                0f
            },
            {
                UnifiedExpression.CheekPuffRight,
                "/cheekPuffRight",
                0f
            },
            {
                UnifiedExpression.CheekSuckLeft,
                "/cheekSuckLeft",
                0f
            },
            {
                UnifiedExpression.CheekSuckRight,
                "/cheekSuckRight",
                0f
            },
            {
                UnifiedExpression.JawOpen,
                "/jawOpen",
                0f
            },
            {
                UnifiedExpression.JawForward,
                "/jawForward",
                0f
            },
            {
                UnifiedExpression.JawLeft,
                "/jawLeft",
                0f
            },
            {
                UnifiedExpression.JawRight,
                "/jawRight",
                0f
            },
            {
                UnifiedExpression.NoseSneerLeft,
                "/noseSneerLeft",
                0f
            },
            {
                UnifiedExpression.NoseSneerRight,
                "/noseSneerRight",
                0f
            },
            {
                UnifiedExpression.LipFunnelLowerLeft,
                "/mouthFunnel",
                0f
            },
            {
                UnifiedExpression.LipFunnelLowerRight,
                "/mouthFunnel",
                0f
            },
            {
                UnifiedExpression.LipFunnelUpperLeft,
                "/mouthFunnel",
                0f
            },
            {
                UnifiedExpression.LipFunnelUpperRight,
                "/mouthFunnel",
                0f
            },
            {
                UnifiedExpression.LipPuckerLowerLeft,
                "/mouthPucker",
                0f
            },
            {
                UnifiedExpression.LipPuckerLowerRight,
                "/mouthPucker",
                0f
            },
            {
                UnifiedExpression.LipPuckerUpperLeft,
                "/mouthPucker",
                0f
            },
            {
                UnifiedExpression.LipPuckerUpperRight,
                "/mouthPucker",
                0f
            },
            {
                UnifiedExpression.MouthUpperLeft,
                "/mouthLeft",
                0f
            },
            {
                UnifiedExpression.MouthLowerLeft,
                "/mouthLeft",
                0f
            },
            {
                UnifiedExpression.MouthUpperRight,
                "/mouthRight",
                0f
            },
            {
                UnifiedExpression.MouthLowerRight,
                "/mouthRight",
                0f
            },
            {
                UnifiedExpression.LipSuckUpperLeft,
                "/mouthRollUpper",
                0f
            },
            {
                UnifiedExpression.LipSuckUpperRight,
                "/mouthRollUpper",
                0f
            },
            {
                UnifiedExpression.LipSuckLowerLeft,
                "/mouthRollLower",
                0f
            },
            {
                UnifiedExpression.LipSuckLowerRight,
                "/mouthRollLower",
                0f
            },
            {
                UnifiedExpression.MouthRaiserUpper,
                "/mouthShrugUpper",
                0f
            },
            {
                UnifiedExpression.MouthRaiserLower,
                "/mouthShrugLower",
                0f
            },
            {
                UnifiedExpression.MouthClosed,
                "/mouthClose",
                0f
            },
            {
                UnifiedExpression.MouthCornerPullLeft,
                "/mouthSmileLeft",
                0f
            },
            {
                UnifiedExpression.MouthCornerPullRight,
                "/mouthSmileRight",
                0f
            },
            {
                UnifiedExpression.MouthFrownLeft,
                "/mouthFrownLeft",
                0f
            },
            {
                UnifiedExpression.MouthFrownRight,
                "/mouthFrownRight",
                0f
            },
            {
                UnifiedExpression.MouthDimpleLeft,
                "/mouthDimpleLeft",
                0f
            },
            {
                UnifiedExpression.MouthDimpleRight,
                "/mouthDimpleRight",
                0f
            },
            {
                UnifiedExpression.MouthUpperUpLeft,
                "/mouthUpperUpLeft",
                0f
            },
            {
                UnifiedExpression.MouthUpperUpRight,
                "/mouthUpperUpRight",
                0f
            },
            {
                UnifiedExpression.MouthLowerDownLeft,
                "/mouthLowerDownLeft",
                0f
            },
            {
                UnifiedExpression.MouthLowerDownRight,
                "/mouthLowerDownRight",
                0f
            },
            {
                UnifiedExpression.MouthPressLeft,
                "/mouthPressLeft",
                0f
            },
            {
                UnifiedExpression.MouthPressRight,
                "/mouthPressRight",
                0f
            },
            {
                UnifiedExpression.MouthStretchLeft,
                "/mouthStretchLeft",
                0f
            },
            {
                UnifiedExpression.MouthStretchRight,
                "/mouthStretchRight",
                0f
            },
            {
                UnifiedExpression.TongueOut,
                "/tongueOut",
                0f
            },
            {
                UnifiedExpression.TongueUp,
                "/tongueUp",
                0f
            },
            {
                UnifiedExpression.TongueDown,
                "/tongueDown",
                0f
            },
            {
                UnifiedExpression.TongueLeft,
                "/tongueLeft",
                0f
            },
            {
                UnifiedExpression.TongueRight,
                "/tongueRight",
                0f
            },
            {
                UnifiedExpression.TongueRoll,
                "/tongueRoll",
                0f
            },
            {
                UnifiedExpression.TongueBendDown,
                "/tongueBendDown",
                0f
            },
            {
                UnifiedExpression.TongueCurlUp,
                "/tongueCurlUp",
                0f
            },
            {
                UnifiedExpression.TongueSquish,
                "/tongueSquish",
                0f
            },
            {
                UnifiedExpression.TongueFlat,
                "/tongueFlat",
                0f
            },
            {
                UnifiedExpression.TongueTwistLeft,
                "/tongueTwistLeft",
                0f
            },
            {
                UnifiedExpression.TongueTwistRight,
                "/tongueTwistRight",
                0f
            }
        };
    }
