using Babble.Core.Enums;
using Babble.OSC.Collections;

namespace Babble.OSC;

public partial class BabbleOSC
{
    public static readonly TwoKeyDictionary<UnifiedExpression, string, float> Expressions = new()
    {
        {
            UnifiedExpression.CheekPuffLeft,
            nameof(UnifiedExpression.CheekPuffLeft),
            0f
        },
        {
            UnifiedExpression.CheekPuffRight,
            nameof(UnifiedExpression.CheekPuffRight),
            0f
        },
        {
            UnifiedExpression.CheekSuckLeft,
            nameof(UnifiedExpression.CheekSuckLeft),
            0f
        },
        {
            UnifiedExpression.CheekSuckRight,
            nameof(UnifiedExpression.CheekSuckRight),
            0f
        },
        {
            UnifiedExpression.JawOpen,
            nameof(UnifiedExpression.JawOpen),
            0f
        },
        {
            UnifiedExpression.JawForward,
            nameof(UnifiedExpression.JawForward),
            0f
        },
        {
            UnifiedExpression.JawLeft,
            nameof(UnifiedExpression.JawLeft),
            0f
        },
        {
            UnifiedExpression.JawRight,
            nameof(UnifiedExpression.JawRight),
            0f
        },
        {
            UnifiedExpression.NoseSneerLeft,
            nameof(UnifiedExpression.NoseSneerLeft),
            0f
        },
        {
            UnifiedExpression.NoseSneerRight,
            nameof(UnifiedExpression.NoseSneerRight),
            0f
        },
        {
            UnifiedExpression.LipFunnelLowerLeft,
            nameof(UnifiedExpression.LipFunnelLowerLeft),
            0f
        },
        {
            UnifiedExpression.LipFunnelLowerRight,
            nameof(UnifiedExpression.LipFunnelLowerRight),
            0f
        },
        {
            UnifiedExpression.LipFunnelUpperLeft,
            nameof(UnifiedExpression.LipFunnelUpperLeft),
            0f
        },
        {
            UnifiedExpression.LipFunnelUpperRight,
            nameof(UnifiedExpression.LipFunnelUpperRight),
            0f
        },
        {
            UnifiedExpression.LipPuckerLowerLeft,
            nameof(UnifiedExpression.LipPuckerLowerLeft),
            0f
        },
        {
            UnifiedExpression.LipPuckerLowerRight,
            nameof(UnifiedExpression.LipPuckerLowerRight),
            0f
        },
        {
            UnifiedExpression.LipPuckerUpperLeft,
            nameof(UnifiedExpression.LipPuckerUpperLeft),
            0f
        },
        {
            UnifiedExpression.LipPuckerUpperRight,
            nameof(UnifiedExpression.LipPuckerUpperRight),
            0f
        },
        {
            UnifiedExpression.MouthUpperLeft,
            nameof(UnifiedExpression.MouthUpperLeft),
            0f
        },
        {
            UnifiedExpression.MouthLowerLeft,
            nameof(UnifiedExpression.MouthLowerLeft),
            0f
        },
        {
            UnifiedExpression.MouthUpperRight,
            nameof(UnifiedExpression.MouthUpperRight),
            0f
        },
        {
            UnifiedExpression.MouthLowerRight,
            nameof(UnifiedExpression.MouthLowerRight),
            0f
        },
        {
            UnifiedExpression.LipSuckUpperLeft,
            nameof(UnifiedExpression.LipSuckUpperLeft),
            0f
        },
        {
            UnifiedExpression.LipSuckUpperRight,
            nameof(UnifiedExpression.LipSuckUpperRight),
            0f
        },
        {
            UnifiedExpression.LipSuckLowerLeft,
            nameof(UnifiedExpression.LipSuckLowerLeft),
            0f
        },
        {
            UnifiedExpression.LipSuckLowerRight,
            nameof(UnifiedExpression.LipSuckLowerRight),
            0f
        },
        {
            UnifiedExpression.MouthRaiserUpper,
            nameof(UnifiedExpression.MouthRaiserUpper),
            0f
        },
        {
            UnifiedExpression.MouthRaiserLower,
            nameof(UnifiedExpression.MouthRaiserLower),
            0f
        },
        {
            UnifiedExpression.MouthClosed,
            nameof(UnifiedExpression.MouthClosed),
            0f
        },
        {
            UnifiedExpression.MouthCornerPullLeft,
            nameof(UnifiedExpression.MouthCornerPullLeft),
            0f
        },
        {
            UnifiedExpression.MouthCornerPullRight,
            nameof(UnifiedExpression.MouthCornerPullRight),
            0f
        },
        {
            UnifiedExpression.MouthFrownLeft,
            nameof(UnifiedExpression.MouthFrownLeft),
            0f
        },
        {
            UnifiedExpression.MouthFrownRight,
            nameof(UnifiedExpression.MouthFrownRight),
            0f
        },
        {
            UnifiedExpression.MouthDimpleLeft,
            nameof(UnifiedExpression.MouthDimpleLeft),
            0f
        },
        {
            UnifiedExpression.MouthDimpleRight,
            nameof(UnifiedExpression.MouthDimpleRight),
            0f
        },
        {
            UnifiedExpression.MouthUpperUpLeft,
            nameof(UnifiedExpression.MouthUpperUpLeft),
            0f
        },
        {
            UnifiedExpression.MouthUpperUpRight,
            nameof(UnifiedExpression.MouthUpperUpRight),
            0f
        },
        {
            UnifiedExpression.MouthLowerDownLeft,
            nameof(UnifiedExpression.MouthLowerDownLeft),
            0f
        },
        {
            UnifiedExpression.MouthLowerDownRight,
            nameof(UnifiedExpression.MouthLowerDownRight),
            0f
        },
        {
            UnifiedExpression.MouthPressLeft,
            nameof(UnifiedExpression.MouthPressLeft),
            0f
        },
        {
            UnifiedExpression.MouthPressRight,
            nameof(UnifiedExpression.MouthPressRight),
            0f
        },
        {
            UnifiedExpression.MouthStretchLeft,
            nameof(UnifiedExpression.MouthStretchLeft),
            0f
        },
        {
            UnifiedExpression.MouthStretchRight,
            nameof(UnifiedExpression.MouthStretchRight),
            0f
        },
        {
            UnifiedExpression.TongueOut,
            nameof(UnifiedExpression.TongueOut),
            0f
        },
        {
            UnifiedExpression.TongueUp,
            nameof(UnifiedExpression.TongueUp),
            0f
        },
        {
            UnifiedExpression.TongueDown,
            nameof(UnifiedExpression.TongueDown),
            0f
        },
        {
            UnifiedExpression.TongueLeft,
            nameof(UnifiedExpression.TongueLeft),
            0f
        },
        {
            UnifiedExpression.TongueRight,
            nameof(UnifiedExpression.TongueRight),
            0f
        },
        {
            UnifiedExpression.TongueRoll,
            nameof(UnifiedExpression.TongueRoll),
            0f
        },
        {
            UnifiedExpression.TongueBendDown,
            nameof(UnifiedExpression.TongueBendDown),
            0f
        },
        {
            UnifiedExpression.TongueCurlUp,
            nameof(UnifiedExpression.TongueCurlUp),
            0f
        },
        {
            UnifiedExpression.TongueSquish,
            nameof(UnifiedExpression.TongueSquish),
            0f
        },
        {
            UnifiedExpression.TongueFlat,
            nameof(UnifiedExpression.TongueFlat),
            0f
        },
        {
            UnifiedExpression.TongueTwistLeft,
            nameof(UnifiedExpression.TongueTwistLeft),
            0f
        },
        {
            UnifiedExpression.TongueTwistRight,
            nameof(UnifiedExpression.TongueTwistRight),
            0f
        }
    };
}
